WebApplication/Models/Cliente/ClienteViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models.Cliente
{
	public class ClienteViewModel
	{
		#region Propriedades
		
		public int Codigo { get; set; }
		public string Nome { get; set; }
		[Display(Name = "Data de nascimento")]
		public DateTime DataNascimento { get; set; } = DateTime.Now.AddYears(-18).Date;
		public string Telefone { get; set; }
		[Display(Name = "E-mail")]
		public string Email { get; set; } 

		#endregion
	}
}

WebApplication/Models/Produto/ProdutoViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebApplication.Infrastructure.Extensions;

namespace WebApplication.Models.Produto
{
	public class ProdutoViewModel
	{
		#region Propriedades

		public int Codigo { get; set; }
		
		[Required]
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		
		[Required]
		[Display(Name = "Preço")]
		public decimal PrecoSugerido { get; set; }
		
		[Display(Name = "Preço")]
		public string PrecoVisualizacao => PrecoSugerido.ToMoneyMask();

		#endregion
	}
}

WebApplication/Models/Venda/ItemVendaViewModel.cs
namespace WebApplication.Models.Venda
{
	public class ItemVendaViewModel
	{
		#region Propriedades

		public int CodigoProduto { get; set; }
		public decimal PrecoUnitario { get; set; }
		public int Quantidade { get; set; }
		public string DescricaoProduto { get; set; }

		#endregion
	}
}

WebApplication/Models/Venda/VendaViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApplication.Infrastructure.Extensions;

namespace WebApplication.Models.Venda
{
	public class VendaViewModel
	{
		#region Propriedades
		public int Codigo { get; set; }
		public int CodigoCliente { get; set; }
		public List<ItemVendaViewModel> ItemVendaViewModelSet { get; set; }
		[Display(Name = "Cliente")]
		public string NomeCliente { get; set; }
		public decimal Total { get; set; }
		[Display(Name = "Total")]
		public string TotalVisualizacao => Total.ToMoneyMask();

		#endregion
	}
}

WebApplication/Controllers/ClienteController.cs
using System.Web.Mvc;
using Servicos.Contratos;
using WebApplication.Infrastructure.Mappers.Contratos;
using WebApplication.Models.Cliente;

namespace WebApplication.Controllers
{
	public class ClienteController : Controller
	{
		#region Ações

		public ActionResult Listar()
		{
			return View(_clienteMapper.Map(_clienteService.Listar()));
		}

		public ActionResult Incluir()
		{
			return View(new ClienteViewModel());
		}
		
		[HttpPost]
		public JsonResult Incluir(ClienteViewModel clienteViewModel)
		{
			return Json(new
			{
				resultado = _clienteService.Incluir(_clienteMapper.Map(clienteViewModel), out var mensagem),
				mensagem
			});
		}

		public ActionResult Alterar(int codigo)
		{
			return View(_clienteMapper.Map(_clienteService.Obter(codigo)));
		}

		[HttpPost]
		public JsonResult Alterar(ClienteViewModel clienteViewModel)
		{
			return Json(new
			{
				resultado = _clienteService.Alterar(_clienteMapper.Map(clienteViewModel), out var mensagem),
				mensagem
			});
		}

		[HttpPost]
		public JsonResult Excluir(int codigo)
		{
			return Json(new
			{
				resultado = _clienteService.Excluir(codigo, out var mensagem),
				mensagem
			});
		}

		#endregion

		#region Campos

		private readonly IClienteMapper _clienteMapper;
		private readonly IClienteService _clienteService;

		#endregion

		#region Construtores

		public ClienteController(IClienteMapper clienteMapper, IClienteService clienteService)
		{
			_clienteMapper = clienteMapper;
			_clienteService = clienteService;
		}

		#endregion
	}
}

WebApplication/Controllers/ProdutoController.cs
using System.Web.Mvc;
using Servicos.Contratos;
using WebApplication.Infrastructure.Mappers.Contratos;
using WebApplication.Models.Produto;

namespace WebApplication.Controllers
{
	public class ProdutoController : Controller
	{
		#region Ações

		public ActionResult Listar()
		{
			return View(_produtoMapper.Map(_produtoService.Listar()));
		}

		public ActionResult Incluir()
		{
			return View(new ProdutoViewModel());
		}
		
		[HttpPost]
		public JsonResult Incluir(ProdutoViewModel produtoViewModel)
		{
			return Json(new
			{
				resultado = _produtoService.Incluir(_produtoMapper.Map(produtoViewModel), out var mensagem),
				mensagem
			});
		}

		public ActionResult Alterar(int codigo)
		{
			return View(_produtoMapper.Map(_produtoService.Obter(codigo)));
		}

		[HttpPost]
		public JsonResult Alterar(ProdutoViewModel produtoViewModel)
		{
			return Json(new
			{
				resultado = _produtoService.Alterar(_produtoMapper.Map(produtoViewModel), out var mensagem),
				mensagem
			});
		}

		[HttpPost]
		public JsonResult Excluir(int codigo)
		{
			return Json(new
			{
				resultado = _produtoService.Excluir(codigo, out var mensagem),
				mensagem
			});
		}

		#endregion

		#region Campos

		private readonly IProdutoMapper _produtoMapper;
		private readonly IProdutoService _produtoService;

		#endregion

		#region Construtores

		public ProdutoController(IProdutoMapper produtoMapper, IProdutoService produtoService)
		{
			_produtoMapper = produtoMapper;
			_produtoService = produtoService;
		}

		#endregion
	}
}

WebApplication/Controllers/VendaController.cs
using System.Web.Mvc;
using Servicos.Contratos;
using WebApplication.Infrastructure.Mappers.Contratos;
using WebApplication.Models.Venda;

namespace WebApplication.Controllers
{
	public class VendaController : Controller
	{
		#region Ações

		public ActionResult Listar()
		{
			return View(_vendaMapper.Map(_vendaService.Listar()));
		}

		public ActionResult SelecionarClientes()
		{
			return View("_SelecionarClientes", _clienteMapper.Map(_clienteService.Listar()));
		}

		public ActionResult SelecionarProdutos()
		{
			return View("_SelecionarProdutos", _produtoMapper.Map(_produtoService.Listar()));
		}

		public ActionResult Incluir()
		{
			return View(new VendaViewModel());
		}

		[HttpPost]
		public JsonResult Incluir(VendaViewModel vendaViewModel)
		{
			return Json(new
			{
				resultado = _vendaService.Incluir(_vendaMapper.Map(vendaViewModel), out var mensagem),
				mensagem
			});
		}

		public ActionResult Alterar(int codigo)
		{
			return View(_vendaMapper.Map(_vendaService.Obter(codigo)));
		}

		[HttpPost]
		public JsonResult Alterar(VendaViewModel vendaViewModel)
		{
			return Json(new
			{
				resultado = _vendaService.Alterar(_vendaMapper.Map(vendaViewModel), out var mensagem),
				mensagem
			});
		}

		[HttpPost]
		public JsonResult Excluir(int codigo)
		{
			return Json(new
			{
				resultado = _vendaService.Excluir(codigo, out var mensagem),
				mensagem
			});
		}

		#endregion

		#region Campos

		private readonly IVendaMapper _vendaMapper;
		private readonly IVendaService _vendaService;
		private readonly IClienteService _clienteService;
		private readonly IClienteMapper _clienteMapper;
		private readonly IProdutoMapper _produtoMapper;
		private readonly IProdutoService _produtoService;


		#endregion

		#region Construtores

		public VendaController(IVendaMapper vendaMapper, IVendaService vendaService, IClienteService clienteService,
			IClienteMapper clienteMapper, IProdutoMapper produtoMapper, IProdutoService produtoService)
		{
			_vendaMapper = vendaMapper;
			_vendaService = vendaService;
			_clienteService = clienteService;
			_clienteMapper = clienteMapper;
			_produtoMapper = produtoMapper;
			_produtoService = produtoService;
		}

		#endregion
	}
}

WebApplication/Views/Cliente/Alterar.cshtml
@model WebApplication.Models.Cliente.ClienteViewModel

@{
	ViewBag.Title = "Cliente";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Cliente/cadastro.js")
}

<h2>Alterar cliente</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Cliente/Incluir.cshtml
@model WebApplication.Models.Cliente.ClienteViewModel

@{
	ViewBag.Title = "Cliente";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Cliente/cadastro.js")
}

<h2>Incluir cliente</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Cliente/Listar.cshtml
@model IEnumerable<WebApplication.Models.Cliente.ClienteViewModel>

@{
	ViewBag.Title = "Clientes";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Cliente/listar.js")
}

<h2>Clientes</h2>

<p>
	@Html.ActionLink("Cadastrar novo cliente", "Incluir")
</p>

@if (Model.Any())
{
	<table class="table table-hover table-striped">
		<tr>
			<th>
				Nome
			</th>
			<th>
				Data de nascimento
			</th>
			<th>
				E-mail
			</th>
			<th>
				Telefone
			</th>
			<th></th>
		</tr>

		@foreach (var clienteViewModel in Model)
		{
		<tr>
			<td>
				@clienteViewModel.Nome
			</td>
			<td>
				@clienteViewModel.DataNascimento.ToShortDateString()
			</td>
			<td>
				@clienteViewModel.Email
			</td>
			<td>
				@clienteViewModel.Telefone
			</td>
			<td>
				@Html.ActionLink("Alterar", "Alterar", new { codigo = clienteViewModel.Codigo })
				<a class="excluir" href="javascript:void(0)" data-codigo="@clienteViewModel.Codigo">Excluir</a>
			</td>
		</tr>
		}

	</table>
}
else
{
	<p>Não há clientes cadastrados</p>
}

WebApplication/Views/Cliente/_Cadastro.cshtml
@model WebApplication.Models.Cliente.ClienteViewModel

<div class="form-horizontal">
	<hr />
	<div class="form-group">
		@Html.LabelFor(model => model.Nome, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="text" id="nome" class="form-control" value="@Model.Nome" />
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.DataNascimento, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="text" data-date-format="dd/mm/yy" id="dataNascimento" class="form-control" value="@Model.DataNascimento" />
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Email, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="email" id="email" class="form-control" value="@Model.Email" />
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Telefone, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="tel" id="telefone" class="form-control" value="@Model.Telefone" />
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-12">
			<input type="submit" id="salvar" value="Salvar" class="btn btn-default btn-success" />
		</div>
	</div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/Produto/Alterar.cshtml
@model WebApplication.Models.Produto.ProdutoViewModel

@{
	ViewBag.Title = "Produto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Produto/cadastro.js")
}

<h2>Alterar produto</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Produto/Incluir.cshtml
@model WebApplication.Models.Produto.ProdutoViewModel

@{
	ViewBag.Title = "Produto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Produto/cadastro.js")
}

<h2>Incluir produto</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Produto/Listar.cshtml
@model IEnumerable<WebApplication.Models.Produto.ProdutoViewModel>

@{
	ViewBag.Title = "Produtos";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Produto/listar.js")
}

<h2>Produtos</h2>

<p>
	@Html.ActionLink("Cadastrar novo produto", "Incluir")
</p>

@if (Model.Any())
{
	<table class="table table-hover table-striped">
		<tr>
			<th>
				Descrição
			</th>
			<th>
				Preço
			</th>
			<th></th>
		</tr>

		@foreach (var produtoViewModel in Model)
		{
			<tr>
				<td>
					@produtoViewModel.Descricao
				</td>
				<td>
					@produtoViewModel.PrecoVisualizacao
				</td>
				<td>
					@Html.ActionLink("Alterar", "Alterar", new { codigo = produtoViewModel.Codigo })
					<a class="excluir" href="javascript:void(0)" data-codigo="@produtoViewModel.Codigo">Excluir</a>
				</td>
			</tr>
		}

	</table>
}
else
{
	<p>Não há produtos cadastrados</p>
}

WebApplication/Views/Produto/_Cadastro.cshtml
@model WebApplication.Models.Produto.ProdutoViewModel

<div class="form-horizontal">
	<hr />
	<div class="form-group">
		@Html.LabelFor(model => model.Descricao, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="text" id="descricao" class="form-control" value="@Model.Descricao"/>
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.PrecoSugerido, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input type="text" id="precoSugerido" class="form-control" value="@Model.PrecoSugerido" />
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-12">
			<input type="submit" id="salvar" value="Salvar" class="btn btn-default btn-success" />
		</div>
	</div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" lang="pt-BR" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	@RenderSection("styles", required: false)
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Sistema de vendas", "Listar", "Venda", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Vendas", "Listar", "Venda")</li>
					<li>@Html.ActionLink("Produtos", "Listar", "Produto")</li>
					<li>@Html.ActionLink("Clientes", "Listar", "Cliente")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year</p>
		</footer>
	</div>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/Scripts/sistema.js")

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<script>
		@{ var url = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/"; }
		var serviceBaseUrl = '@url';
	</script>

	@RenderSection("scripts", required: false)
</body>
</html>

WebApplication/Views/Venda/Alterar.cshtml
@model WebApplication.Models.Venda.VendaViewModel

@{
	ViewBag.Title = "Venda";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
	@Styles.Render("~/Content/Venda/venda.css")
}

@section scripts {
	@Scripts.Render("~/Scripts/Venda/cadastro.js")
}

<h2>Alterar venda</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Venda/Incluir.cshtml
@model WebApplication.Models.Venda.VendaViewModel

@{
	ViewBag.Title = "Venda";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
	@Styles.Render("~/Content/Venda/venda.css")
}

@section scripts {
	@Scripts.Render("~/Scripts/Venda/cadastro.js")
}

<h2>Incluir venda</h2>

@Html.Partial("_Cadastro", Model)

WebApplication/Views/Venda/Listar.cshtml
@model IEnumerable<WebApplication.Models.Venda.VendaViewModel>

@{
	ViewBag.Title = "Vendas";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
	@Scripts.Render("~/Scripts/Venda/listar.js")
}

<h2>Vendas</h2>

<p>
	@Html.ActionLink("Cadastrar nova venda", "Incluir")
</p>

@if (Model.Any())
{
	<table class="table table-hover table-striped">
		<tr>
			<th>
				Cliente
			</th>
			<th>
				Total
			</th>
			<th></th>
		</tr>

		@foreach (var vendaViewModel in Model)
		{
		<tr>
			<td>
				@vendaViewModel.NomeCliente
			</td>
			<td>
				@vendaViewModel.TotalVisualizacao
			</td>
			<td>
				<a class="excluir" href="javascript:void(0)" data-codigo="@vendaViewModel.Codigo">Excluir</a>
			</td>
		</tr>
		}

	</table>
}
else
{
	<p>Não há vendas cadastrados</p>
}

WebApplication/Views/Venda/_Cadastro.cshtml
@model WebApplication.Models.Venda.VendaViewModel

<div class="form-horizontal">
	<hr />

	<div class="form-group">
		@Html.LabelFor(model => model.NomeCliente, new { @class = "col-md-12" })
		<div class="col-md-12">
			<input id="codigoCliente" type="hidden" value="@Model.CodigoCliente" />
			<input id="nomeCliente" type="text" class="form-control nomeCliente" value="@Model.NomeCliente" readonly="readonly" />
			<a id="selecionarCliente" title="Selecionar cliente" class="selecionarButton selecaoCliente" href="javascript:void(0)"><i class="glyphicon glyphicon-list-alt"></i></a>
		</div>
	</div>

	<hr />
	
	<div class="row">
		<div class="col-lg-4">
			<div class="form-group">
				<div class="col-md-12">
					<label>Produto</label>
				</div>
				<div class="col-md-12">
					<input id="codigoProduto" type="hidden" />
					<input id="descricaoProduto" type="text" class="form-control nomeProduto" readonly="readonly" />
					<a id="selecionarProduto" title="Selecionar produto" class="selecionarButton selecaoProduto" href="javascript:void(0)"><i class="glyphicon glyphicon-list-alt"></i></a>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
			<div class="form-group">
				<div class="col-md-12">
					<label>Valor</label>
				</div>
				<div class="col-md-12">
					<input id="precoProduto" type="text" class="form-control valorProduto"/>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
			<div class="form-group">
				<div class="col-md-12">
					<label>Quantidade</label>
				</div>
				<div class="col-md-12">
					<input id="quantidadeProduto" type="number" class="form-control quantidadeProduto" />
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
				<div class="col-md-12">
					<button id="adicionarProduto" type="button" class="btn btn-info">
						<span class="glyphicon glyphicon-plus"></span> Adicionar
					</button>
				</div>
			</div>
		</div>
	</div>

		<hr />

		<table class="table table-hover table-striped" id="itensVenda">
			<thead>
				<tr>
					<th>
						Produto
					</th>
					<th>
						Valor unitário
					</th>
					<th>
						Quantidade
					</th>
					<th>
						Valor total
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>

		<div class="form-group">
			<div class="col-md-12">
				<input type="submit" id="salvar" value="Salvar" class="btn btn-default btn-success" />
			</div>
		</div>
	</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/Venda/_SelecionarClientes.cshtml
@model IEnumerable<WebApplication.Models.Cliente.ClienteViewModel>
@{
	Layout = null;
}

<p>
	<h2>Selecionar cliente</h2>
</p>
<table class="table table-striped">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Nome)
		</th>
		<th></th>
	</tr>

	@foreach (var clienteViewModel in Model) {
		<tr>
			<td>
				@Html.DisplayFor(modelItem => clienteViewModel.Nome)
			</td>
			<td>
				<a href="javascrip:void(0)" class="selecionouCliente" data-codigo="@clienteViewModel.Codigo" data-nome="@clienteViewModel.Nome">Selecionar</a>
			</td>
		</tr>
	}
</table>

WebApplication/Views/Venda/_SelecionarProdutos.cshtml
@model IEnumerable<WebApplication.Models.Produto.ProdutoViewModel>
@{
	Layout = null;
}

<p>
	<h2>Selecionar produto</h2>
</p>
<table class="table table-striped">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Descricao)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.PrecoVisualizacao)
		</th>
		<th></th>
	</tr>

	@foreach (var produtoViewModel in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => produtoViewModel.Descricao)
		</td>
		<td>
			@Html.DisplayFor(modelItem => produtoViewModel.PrecoVisualizacao)
		</td>
		<td>
			<a href="javascrip:void(0)" class="selecionouProduto" data-codigo="@produtoViewModel.Codigo" data-descricao="@produtoViewModel.Descricao" data-preco="@produtoViewModel.PrecoSugerido">Selecionar</a>
		</td>
	</tr>
	}
</table>